before_install:
- "sudo apt-get update && sudo apt-get install --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra texlive-latex-recommended dvipng pgf"

env:
  matrix:
    - TARGET=test language=python
    - TARGET=results
    - TARGET=article
    - TARGET=code language=python

script:
  - travis_wait make $TARGET

notifications:
  email: false
