before_install:
- "sudo apt-get update && sudo apt-get install --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra texlive-latex-recommended dvipng pgf"

language: python

env:
  matrix:
    - TARGET=test
    - TARGET=results
    - TARGET=article
    - TARGET=code

script:
  - travis_wait 60 make $TARGET

notifications:
  email: false
