before_install:
- "sudo apt-get update && sudo apt-get install --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra texlive-latex-recommended dvipng pgf"

env:
  matrix:
    - TARGET=test
    - TARGET=results
    - TARGET=article

script:
  - make $TARGET

notifications:
  email: false
