FROM poetry:0.1


WORKDIR /tmp/working

RUN pip install --no-cache-dir poetry

COPY pyproject.toml
COPY poetry.lock .

RUN poetry install

COPY main.py .
COPY spec.py .
ENV DEST_FOLDER /aci/output
CMD [ "python", "./main.py" ]

