
name: Docker image on ACR

on:
  push:
    branches: 
      - docker_search

jobs:
  detect_files:
    if: contains( github.event.head_commit.message, '[build')
    name: Detect files
    runs-on: ubuntu-latest
    outputs:
        matrix: ${{ steps.set-matrix.outputs.matrix }}
        tag: ${{ steps.set-name.outputs.tag }}
    steps:
    - uses: actions/checkout@v2
    - id: set-matrix
      name: Write files to matrix
      run: python3 -m helpers.list_tasks
    - id: set-name
      name: Get tag prefix for images
      run: python3 -m helpers.tag_name
  build_images:
    if: contains( github.event.head_commit.message, '[build')
    name: Build Docker images
    runs-on: ubuntu-latest
    needs: detect_files
    strategy:
      matrix: ${{fromJson(needs.detect_files.outputs.matrix)}}
    steps:
    
    - name: Checkout
      uses: actions/checkout@v2

    - name: Copy task file
      id: copy_t
      run: cp $GITHUB_WORKSPACE/docker_config/tasks/${{ matrix.taskfile }} $GITHUB_WORKSPACE/docker_config/spec.py

    - name: build image
      run: |
          az login --service-principal -u ${{ secrets.ACR_SP_NAME }} -p ${{ secrets.ACR_SP_PASSWORD }} --tenant ${{ secrets.ACR_TENANT }}
          az acr build -r ${{ secrets.ACR_REGISTRY }} -f $GITHUB_WORKSPACE/docker_config/Dockerfile -t ${{ secrets.ACR_REPOSITORY }}/basic_search:${{ needs.detect_files.outputs.tag }}_${{ matrix.name }} $GITHUB_WORKSPACE/docker_config/
