
name: Docker image on ACR

on:
  push:
    branches: 
      - docker_search

jobs:
  detect_files:
    name: Detect files
    runs-on: ubuntu-latest
    outputs:
        matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - id: set-matrix
      name: Write files to matrix
      run: python -m helpers.list_tasks
  build_images:
    name: Build Docker images
    runs-on: ubuntu-latest
    needs: detect_files
    strategy:
      matrix: ${{fromJson(needs.detect_files.outputs.matrix)}}
    steps:
    - uses: actions/checkout@v2
    - name: Copy task file
      id: copy_t
      run: cp docker_config/tasks/${{ matrix.taskfile }} docker_config/spec.py
    - name: ACR build
      id: acr
      uses: ams0/acr-task-github-action@v2
      with:
        service_principal: ${{ secrets.ACR_SP_NAME }}
        service_principal_password: ${{ secrets.ACR_SP_PASSWORD }}
        tenant: ${{ secrets.ACR_TENANT }}
        registry: ${{ secrets.ACR_REGISTRY }}
        repository: ${{ secrets.ACR_REPOSITORY }}
        image: basic_search
        folder: docker_config
        tag: ${{ matrix.name }}
