
name: Docker image on ACR

on:
  push:
    branches: 
      - minimal_docker_run

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: ACR build
      id: acr
      uses: ams0/acr-task-github-action@v1
      with:
        service_principal: ${{ secrets.ACR_SP_NAME }}
        service_principal_password: ${{ secrets.ACR_SP_PASSWORD }}
        tenant: ${{ secrets.ACR_TENANT }}
        registry: ${{ secrets.ACR_REGISTRY }}
        repository: ${{ secrets.ACR_REPOSITORY }}
        image: minimal
        folder: docker_config
        branch: minimal_docker_run
