
name: Create docker image

on:
  push:
    branches: 
      - minimal_docker_run
      - docker_search

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Copy a file
      run: cp docker_config/tasks/old/0004.py docker_config/spec.py
    - name: Build the Docker image
      run: docker build --tag t-tetromino/minimal:$(date +%s) docker_config/
