
name: Create docker image

on:
  push:
    branches: 
      - minimal_docker_run

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build --tag t-tetromino/minimal:$(date +%s) docker_config/
