name: Run tests on results

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Set up Python
      run: |
        cd results/
        pip install -r requirements.txt
    - name: Run tests
      run: |
        cd results/
        python -m pytest
        
